apiVersion: skaffold/v2beta25
kind: Config
deploy:
  kubectl:
    manifests:
      - "./k8s/*.yaml"
build:
  local:
    push: false
  artifacts:
    - image: zhunus/auth
      context: ../packages/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: zhunus/client
      context: ../packages/client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: zhunus/remix
      context: ../packages/remix
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "app/**/*"
            dest: .
    - image: zhunus/tickets
      context: ../packages/tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: zhunus/orders
      context: ../packages/orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
